name = "dataset-z09-solve-cache"
main = "src/index.ts"
compatibility_date = "2026-03-28"
workers_dev = true

kv_namespaces = [
  { binding = "SOLVE_CACHE", id = "ac0047d6f8a3444ebf65aeb9d72c1011", preview_id = "5190065978e7479e8e7d104fe3226ccb" }
]

vectorize = [
  { binding = "SOLVE_CACHE_VECTOR_P4", index_name = "dataset-z09-solve-cache-p4" }
]

routes = [
  { pattern = "hd-cache.tscircuit.com", custom_domain = true }
]

[vars]
MAX_SOLVE_CACHE_CANDIDATES_TO_TRY = "16"
SOLVER_MAX_ITERATIONS = "250000"
TRACE_WIDTH = "0.1"
VIA_DIAMETER = "0.3"
